### ISSUE TITLE
移除已过时的 `community` repo

### ISSUE THREAD

**Issue by pizeroLOL** [CatOS-Home/CatOS#7]
https://github.com/CatOS-Home/CatOS/blob/c635e3b3def08865c965b3e27463dac264ee3e61/catos-iso-for-nvidia/pacman.conf#L82-L86

https://github.com/CatOS-Home/CatOS/blob/c635e3b3def08865c965b3e27463dac264ee3e61/catos-iso/pacman.conf#L82-L86

如[官方新闻](https://archlinux.org/news/git-migration-completed/)所示，community 源已经被移动到 extra 源里了，能否移除 pacman.conf 里的 community 源？

**Comment by CatOS-Home** [comment]
已移除pacman.conf中已过时的 community repo，感谢您的反馈！
